<a href="https://colab.research.google.com/github/parvesh7o7/Data-Science-Learning/blob/main/real_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/car_crashes.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   total           51 non-null     float64
 1   speeding        51 non-null     float64
 2   alcohol         51 non-null     float64
 3   not_distracted  51 non-null     float64
 4   no_previous     51 non-null     float64
 5   ins_premium     51 non-null     float64
 6   ins_losses      51 non-null     float64
 7   abbrev          51 non-null     object
dtypes: float64(7), object(1)
memory usage: 3.3+ KB

In [ ]:
df.loc[df['alcohol']>5, ['abbrev', 'alcohol']]

   abbrev  alcohol
0      AL    5.640
2      AZ    5.208
3      AR    5.824
9      FL    5.191
11     HI    7.175
18     LA    6.765
24     MS    5.456
25     MO    5.474
26     MT    9.416
27     NE    5.215
33     NC    5.208
34     ND   10.038
36     OK    5.771
38     PA    5.642
40     SC    9.799
41     SD    6.402
42     TN    5.655
43     TX    7.372
48     WV    6.664
50     WY    5.568

In [ ]:
(df['alcohol']>5).sum()

np.int64(20)

In [ ]:
grouped = df.groupby(by='abbrev')

In [ ]:
for state, data in grouped:
  print(state)
  print(data)

AK
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
1   18.1     7.421    4.525           16.29       17.014      1053.48

   ins_losses abbrev
1      133.93     AK
AL
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332     5.64          18.048        15.04       784.55

   ins_losses abbrev
0      145.08     AL
AR
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
3   22.4     4.032    5.824          21.056        21.28       827.34

   ins_losses abbrev
3      142.39     AR
AZ
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
2   18.6      6.51    5.208          15.624       17.856       899.47

   ins_losses abbrev
2      110.35     AZ
CA
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
4   12.0       4.2     3.36           10.92        10.68       878.41

   ins_losses abbrev
4      165.63     CA
CO
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
5   13.6     5.032    3.808          10.744        12.92        835.5

   ins_losses abbrev
5      139.91     CO
CT
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
6   10.8     4.968    3.888           9.396        8.856      1068.73

   ins_losses abbrev
6      167.02     CT
DC
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
8    5.9     2.006    1.593             5.9          5.9      1273.89

   ins_losses abbrev
8      136.05     DC
DE
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
7   16.2     6.156     4.86          14.094       16.038      1137.87

   ins_losses abbrev
7      151.48     DE
FL
   total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
9   17.9     3.759    5.191          16.468       16.826      1160.13

   ins_losses abbrev
9      144.18     FL
GA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
10   15.6     2.964      3.9           14.82       14.508       913.15

    ins_losses abbrev
10       142.8     GA
HI
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
11   17.5      9.45    7.175           14.35       15.225       861.18

    ins_losses abbrev
11      120.92     HI
IA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
15   15.7     2.669    3.925          15.229       13.659       649.06

    ins_losses abbrev
15      114.47     IA
ID
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
12   15.3     5.508    4.437          13.005       14.994       641.96

    ins_losses abbrev
12       82.75     ID
IL
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
13   12.8     4.608    4.352          12.032       12.288       803.11

    ins_losses abbrev
13      139.15     IL
IN
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
14   14.5     3.625    4.205          13.775       13.775       710.46

    ins_losses abbrev
14      108.92     IN
KS
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
16   17.8     4.806    4.272          13.706        15.13       780.45

    ins_losses abbrev
16       133.8     KS
KY
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
17   21.4     4.066    4.922          16.692       16.264       872.51

    ins_losses abbrev
17      137.13     KY
LA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
18   20.5     7.175    6.765          14.965        20.09      1281.55

    ins_losses abbrev
18      194.78     LA
MA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
21    8.2     1.886     2.87           7.134         6.56      1011.14

    ins_losses abbrev
21      135.63     MA
MD
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
20   12.5      4.25      4.0           8.875       12.375      1048.78

    ins_losses abbrev
20       192.7     MD
ME
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
19   15.1     5.738     4.53          13.137       12.684       661.88

    ins_losses abbrev
19       96.57     ME
MI
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
22   14.1     3.384    3.948          13.395       10.857      1110.61

    ins_losses abbrev
22      152.26     MI
MN
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
23    9.6     2.208    2.784           8.448        8.448       777.18

    ins_losses abbrev
23      133.35     MN
MO
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
25   16.1     6.923    5.474          14.812       13.524       790.32

    ins_losses abbrev
25      144.45     MO
MS
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
24   17.6      2.64    5.456            1.76         17.6       896.07

    ins_losses abbrev
24      155.77     MS
MT
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
26   21.4     8.346    9.416          17.976        18.19       816.21

    ins_losses abbrev
26       85.15     MT
NC
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
33   16.8     6.552    5.208          15.792       13.608       708.24

    ins_losses abbrev
33      127.82     NC
ND
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
34   23.9     5.497   10.038          23.661       20.554       688.75

    ins_losses abbrev
34      109.72     ND
NE
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
27   14.9     1.937    5.215          13.857        13.41       732.28

    ins_losses abbrev
27      114.82     NE
NH
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
29   11.6      4.06     3.48          10.092        9.628       746.54

    ins_losses abbrev
29      120.21     NH
NJ
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
30   11.2     1.792    3.136           9.632        8.736      1301.52

    ins_losses abbrev
30      159.85     NJ
NM
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
31   18.4     3.496    4.968          12.328       18.032       869.85

    ins_losses abbrev
31      120.75     NM
NV
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
28   14.7     5.439    4.704          13.965       14.553      1029.87

    ins_losses abbrev
28      138.71     NV
NY
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
32   12.3     3.936    3.567          10.824         9.84      1234.31

    ins_losses abbrev
32      150.01     NY
OH
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
35   14.1     3.948    4.794          13.959       11.562       697.73

    ins_losses abbrev
35      133.52     OH
OK
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
36   19.9     6.368    5.771          18.308       18.706       881.51

    ins_losses abbrev
36      178.86     OK
OR
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
37   12.8     4.224    3.328           8.576        11.52       804.71

    ins_losses abbrev
37      104.61     OR
PA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
38   18.2       9.1    5.642          17.472       16.016       905.99

    ins_losses abbrev
38      153.86     PA
RI
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
39   11.1     3.774    4.218          10.212        8.769      1148.99

    ins_losses abbrev
39      148.58     RI
SC
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
40   23.9     9.082    9.799          22.944       19.359       858.97

    ins_losses abbrev
40      116.29     SC
SD
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
41   19.4     6.014    6.402          19.012       16.684       669.31

    ins_losses abbrev
41       96.87     SD
TN
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
42   19.5     4.095    5.655           15.99       15.795       767.91

    ins_losses abbrev
42      155.57     TN
TX
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
43   19.4      7.76    7.372          17.654       16.878      1004.75

    ins_losses abbrev
43      156.83     TX
UT
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
44   11.3     4.859    1.808           9.944       10.848       809.38

    ins_losses abbrev
44      109.48     UT
VA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
46   12.7     2.413    3.429          11.049       11.176       768.95

    ins_losses abbrev
46      153.72     VA
VT
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
45   13.6      4.08     4.08          13.056        12.92        716.2

    ins_losses abbrev
45      109.61     VT
WA
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
47   10.6     4.452    3.498           8.692        9.116       890.03

    ins_losses abbrev
47      111.62     WA
WI
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
49   13.8     4.968    4.554           5.382       11.592       670.31

    ins_losses abbrev
49      106.62     WI
WV
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
48   23.8     8.092    6.664          23.086       20.706       992.61

    ins_losses abbrev
48      152.56     WV
WY
    total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
50   17.4     7.308    5.568          14.094        15.66       791.14

    ins_losses abbrev
50      122.04     WY

In [ ]:
print(grouped.count())

        total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
abbrev
AK          1         1        1               1            1            1
AL          1         1        1               1            1            1
AR          1         1        1               1            1            1
AZ          1         1        1               1            1            1
CA          1         1        1               1            1            1
CO          1         1        1               1            1            1
CT          1         1        1               1            1            1
DC          1         1        1               1            1            1
DE          1         1        1               1            1            1
FL          1         1        1               1            1            1
GA          1         1        1               1            1            1
HI          1         1        1               1            1            1
IA          1         1        1               1            1            1
ID          1         1        1               1            1            1
IL          1         1        1               1            1            1
IN          1         1        1               1            1            1
KS          1         1        1               1            1            1
KY          1         1        1               1            1            1
LA          1         1        1               1            1            1
MA          1         1        1               1            1            1
MD          1         1        1               1            1            1
ME          1         1        1               1            1            1
MI          1         1        1               1            1            1
MN          1         1        1               1            1            1
MO          1         1        1               1            1            1
MS          1         1        1               1            1            1
MT          1         1        1               1            1            1
NC          1         1        1               1            1            1
ND          1         1        1               1            1            1
NE          1         1        1               1            1            1
NH          1         1        1               1            1            1
NJ          1         1        1               1            1            1
NM          1         1        1               1            1            1
NV          1         1        1               1            1            1
NY          1         1        1               1            1            1
OH          1         1        1               1            1            1
OK          1         1        1               1            1            1
OR          1         1        1               1            1            1
PA          1         1        1               1            1            1
RI          1         1        1               1            1            1
SC          1         1        1               1            1            1
SD          1         1        1               1            1            1
TN          1         1        1               1            1            1
TX          1         1        1               1            1            1
UT          1         1        1               1            1            1
VA          1         1        1               1            1            1
VT          1         1        1               1            1            1
WA          1         1        1               1            1            1
WI          1         1        1               1            1            1
WV          1         1        1               1            1            1
WY          1         1        1               1            1            1

        ins_losses
abbrev
AK               1
AL               1
AR               1
AZ               1
CA               1
CO               1
CT               1
DC               1
DE               1
FL               1
GA               1
HI               1
IA               1
ID               1
IL               1
IN               1
KS               1
KY               1
LA               1
MA               1
MD               1
ME               1
MI               1
MN               1
MO               1
MS               1
MT               1
NC               1
ND               1
NE               1
NH               1
NJ               1
NM               1
NV               1
NY               1
OH               1
OK               1
OR               1
PA               1
RI               1
SC               1
SD               1
TN               1
TX               1
UT               1
VA               1
VT               1
WA               1
WI               1
WV               1
WY               1

In [ ]:
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [ ]:
grouped.size()

abbrev
AK    1
AL    1
AR    1
AZ    1
CA    1
CO    1
CT    1
DC    1
DE    1
FL    1
GA    1
HI    1
IA    1
ID    1
IL    1
IN    1
KS    1
KY    1
LA    1
MA    1
MD    1
ME    1
MI    1
MN    1
MO    1
MS    1
MT    1
NC    1
ND    1
NE    1
NH    1
NJ    1
NM    1
NV    1
NY    1
OH    1
OK    1
OR    1
PA    1
RI    1
SC    1
SD    1
TN    1
TX    1
UT    1
VA    1
VT    1
WA    1
WI    1
WV    1
WY    1
dtype: int64

In [3]:
adult_db = pd.read_csv("adult11.csv")

In [ ]:
adult_db.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,salary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
grouped.size().sort_values(ascending=False)

abbrev
AK    1
AL    1
AR    1
AZ    1
CA    1
CO    1
CT    1
DC    1
DE    1
FL    1
GA    1
HI    1
IA    1
ID    1
IL    1
IN    1
KS    1
KY    1
LA    1
MA    1
MD    1
ME    1
MI    1
MN    1
MO    1
MS    1
MT    1
NC    1
ND    1
NE    1
NH    1
NJ    1
NM    1
NV    1
NY    1
OH    1
OK    1
OR    1
PA    1
RI    1
SC    1
SD    1
TN    1
TX    1
UT    1
VA    1
VT    1
WA    1
WI    1
WV    1
WY    1
dtype: int64

In [ ]:
grouped.size().idxmax()

'AK'

In [ ]:
grouped.mean().sort_values(by='total', ascending=False)

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses
abbrev,,,,,,,
ND,23.9,5.497,10.038,23.661,20.554,688.75,109.72
SC,23.9,9.082,9.799,22.944,19.359,858.97,116.29
WV,23.8,8.092,6.664,23.086,20.706,992.61,152.56
AR,22.4,4.032,5.824,21.056,21.280,827.34,142.39
MT,21.4,8.346,9.416,17.976,18.190,816.21,85.15
KY,21.4,4.066,4.922,16.692,16.264,872.51,137.13
LA,20.5,7.175,6.765,14.965,20.090,1281.55,194.78
OK,19.9,6.368,5.771,18.308,18.706,881.51,178.86
TN,19.5,4.095,5.655,15.990,15.795,767.91,155.57
TX,19.4,7.760,7.372,17.654,16.878,1004.75,156.83
SD,19.4,6.014,6.402,19.012,16.684,669.31,96.87
AL,18.8,7.332,5.640,18.048,15.040,784.55,145.08
AZ,18.6,6.510,5.208,15.624,17.856,899.47,110.35
NM,18.4,3.496,4.968,12.328,18.032,869.85,120.75
PA,18.2,9.100,5.642,17.472,16.016,905.99,153.86
AK,18.1,7.421,4.525,16.290,17.014,1053.48,133.93
FL,17.9,3.759,5.191,16.468,16.826,1160.13,144.18
KS,17.8,4.806,4.272,13.706,15.130,780.45,133.80
MS,17.6,2.640,5.456,1.760,17.600,896.07,155.77
HI,17.5,9.450,7.175,14.350,15.225,861.18,120.92
WY,17.4,7.308,5.568,14.094,15.660,791.14,122.04
NC,16.8,6.552,5.208,15.792,13.608,708.24,127.82
DE,16.2,6.156,4.860,14.094,16.038,1137.87,151.48
MO,16.1,6.923,5.474,14.812,13.524,790.32,144.45
IA,15.7,2.669,3.925,15.229,13.659,649.06,114.47
GA,15.6,2.964,3.900,14.820,14.508,913.15,142.80
ID,15.3,5.508,4.437,13.005,14.994,641.96,82.75
ME,15.1,5.738,4.530,13.137,12.684,661.88,96.57
NE,14.9,1.937,5.215,13.857,13.410,732.28,114.82
NV,14.7,5.439,4.704,13.965,14.553,1029.87,138.71
IN,14.5,3.625,4.205,13.775,13.775,710.46,108.92
MI,14.1,3.384,3.948,13.395,10.857,1110.61,152.26
OH,14.1,3.948,4.794,13.959,11.562,697.73,133.52
WI,13.8,4.968,4.554,5.382,11.592,670.31,106.62
CO,13.6,5.032,3.808,10.744,12.920,835.50,139.91
VT,13.6,4.080,4.080,13.056,12.920,716.20,109.61
OR,12.8,4.224,3.328,8.576,11.520,804.71,104.61
IL,12.8,4.608,4.352,12.032,12.288,803.11,139.15
VA,12.7,2.413,3.429,11.049,11.176,768.95,153.72
MD,12.5,4.250,4.000,8.875,12.375,1048.78,192.70
NY,12.3,3.936,3.567,10.824,9.840,1234.31,150.01
CA,12.0,4.200,3.360,10.920,10.680,878.41,165.63
NH,11.6,4.060,3.480,10.092,9.628,746.54,120.21
UT,11.3,4.859,1.808,9.944,10.848,809.38,109.48
NJ,11.2,1.792,3.136,9.632,8.736,1301.52,159.85
RI,11.1,3.774,4.218,10.212,8.769,1148.99,148.58
CT,10.8,4.968,3.888,9.396,8.856,1068.73,167.02
WA,10.6,4.452,3.498,8.692,9.116,890.03,111.62
MN,9.6,2.208,2.784,8.448,8.448,777.18,133.35
MA,8.2,1.886,2.870,7.134,6.560,1011.14,135.63
DC,5.9,2.006,1.593,5.900,5.900,1273.89,136.05

In [ ]:
(adult_db['hours-per-week']>50).sum()

np.int64(5435)

In [ ]:
adult_db.loc[adult_db['hours-per-week']>50]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,salary
25,45,Self-emp-not-inc,432824,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,7298,0,90,United-States,>50K
27,23,Private,134446,HS-grad,9,Separated,Machine-op-inspct,Unmarried,Black,Male,0,0,54,United-States,<=50K
29,32,Self-emp-not-inc,109282,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,60,United-States,<=50K
53,22,Private,54164,HS-grad,9,Never-married,Other-service,Not-in-family,White,Male,14084,0,60,United-States,>50K
54,38,Private,219446,9th,5,Married-spouse-absent,Exec-managerial,Not-in-family,White,Male,0,0,54,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48811,35,?,320084,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,55,United-States,>50K
48812,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
48813,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
48817,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
48829,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K

In [ ]:
adult_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       48842 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      48842 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   gender          48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48842 non-null  object
 14  salary          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
edu_level = adult_db.groupby(by='education').size()
edu_level

education
10th             1389
11th             1812
12th              657
1st-4th           247
5th-6th           509
7th-8th           955
9th               756
Assoc-acdm       1601
Assoc-voc        2061
Bachelors        8025
Doctorate         594
HS-grad         15784
Masters          2657
Preschool          83
Prof-school       834
Some-college    10878
dtype: int64

In [ ]:
edu_level.max()

15784

In [ ]:
edu_level.idxmax()

'HS-grad'

In [ ]:
grp_occupation = adult_db.groupby(by='occupation')
grp_occupation.size()

occupation
?                    2809
Adm-clerical         5611
Armed-Forces           15
Craft-repair         6112
Exec-managerial      6086
Farming-fishing      1490
Handlers-cleaners    2072
Machine-op-inspct    3022
Other-service        4923
Priv-house-serv       242
Prof-specialty       6172
Protective-serv       983
Sales                5504
Tech-support         1446
Transport-moving     2355
dtype: int64

In [ ]:
avg_hours = grp_occupation['hours-per-week'].mean()
avg_hours

occupation
?                    31.802065
Adm-clerical         37.708073
Armed-Forces         41.600000
Craft-repair         42.269306
Exec-managerial      44.975353
Farming-fishing      46.817450
Handlers-cleaners    37.911197
Machine-op-inspct    40.778623
Other-service        34.751980
Priv-house-serv      33.024793
Prof-specialty       42.282890
Protective-serv      42.789420
Sales                40.749273
Tech-support         39.720609
Transport-moving     44.727389
Name: hours-per-week, dtype: float64

In [ ]:
avg_hours.idxmax()

'Farming-fishing'

In [ ]:
age_grp = adult_db.groupby(by='age')
age_grp.size()

age
17     595
18     862
19    1053
20    1113
21    1096
      ...
86       1
87       3
88       6
89       2
90      55
Length: 74, dtype: int64

In [ ]:
age_grp['hours-per-week'].mean()

age
17    21.137815
18    25.745940
19    30.560304
20    32.432165
21    34.252737
        ...
86    40.000000
87     7.000000
88    35.833333
89    30.000000
90    37.654545
Name: hours-per-week, Length: 74, dtype: float64

In [ ]:
gender_grp = adult_db.groupby(by='gender')
gender_grp.size()

gender
Female    16192
Male      32650
dtype: int64

In [ ]:
gender_grp['age'].mean()

gender
Female    36.927989
Male      39.494395
Name: age, dtype: float64

In [ ]:
gender_grp['hours-per-week'].mean()

gender
Female    36.400692
Male      42.416845
Name: hours-per-week, dtype: float64

In [ ]:
#agg function
gender_grp.agg({
    'age': ['count', 'mean'],
    'hours-per-week': ['mean']
})

          age            hours-per-week
        count       mean           mean
gender
Female  16192  36.927989      36.400692
Male    32650  39.494395      42.416845

In [ ]:
greater_than_50k = adult_db.loc[adult_db['salary']=='>50K']
grp_edu = greater_than_50k.groupby(by='education')

In [ ]:
grp_edu.size().idxmax()

'Bachelors'

In [4]:
adult_db.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,salary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [16]:
salary_grouped = adult_db.loc[adult_db['salary']=='>50K']

In [19]:
salary_grouped.groupby(by='education').size()

education
10th              87
11th              92
12th              48
1st-4th            8
5th-6th           27
7th-8th           62
9th               41
Assoc-acdm       413
Assoc-voc        522
Bachelors       3313
Doctorate        431
HS-grad         2503
Masters         1459
Preschool          1
Prof-school      617
Some-college    2063
dtype: int64

In [21]:
edu_level = adult_db.groupby(by='education')

In [22]:
edu_level.size()

education
10th             1389
11th             1812
12th              657
1st-4th           247
5th-6th           509
7th-8th           955
9th               756
Assoc-acdm       1601
Assoc-voc        2061
Bachelors        8025
Doctorate         594
HS-grad         15784
Masters          2657
Preschool          83
Prof-school       834
Some-college    10878
dtype: int64

In [29]:
percentage = (salary_grouped.groupby(by='education').size()/edu_level.size() * 100).sort_values(ascending=False)

In [30]:
percentage

education
Prof-school     73.980815
Doctorate       72.558923
Masters         54.911554
Bachelors       41.283489
Assoc-acdm      25.796377
Assoc-voc       25.327511
Some-college    18.964883
HS-grad         15.857831
12th             7.305936
7th-8th          6.492147
10th             6.263499
9th              5.423280
5th-6th          5.304519
11th             5.077263
1st-4th          3.238866
Preschool        1.204819
dtype: float64

In [33]:
high_earner = adult_db[adult_db['salary']=='>50K'].groupby(by='education')

In [35]:
high_earner.size()

education
10th              87
11th              92
12th              48
1st-4th            8
5th-6th           27
7th-8th           62
9th               41
Assoc-acdm       413
Assoc-voc        522
Bachelors       3313
Doctorate        431
HS-grad         2503
Masters         1459
Preschool          1
Prof-school      617
Some-college    2063
dtype: int64

In [36]:
salary_grouped.groupby(by='education').size()

education
10th              87
11th              92
12th              48
1st-4th            8
5th-6th           27
7th-8th           62
9th               41
Assoc-acdm       413
Assoc-voc        522
Bachelors       3313
Doctorate        431
HS-grad         2503
Masters         1459
Preschool          1
Prof-school      617
Some-college    2063
dtype: int64

In [37]:
#Do people who work 40+ hours per week earn more than >50K compared to those who work less than 40 hours?
#Calculate the percentage of high-earners (>50K) in each group.
#Which group has higher percentage?

In [38]:
adult_db.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,salary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [54]:
high_earner = adult_db[adult_db['salary']=='>50K']
high_earner.loc[high_earner['hours-per-week']>40].count()

age               5742
workclass         5742
fnlwgt            5742
education         5742
education-num     5742
marital-status    5742
occupation        5742
relationship      5742
race              5742
gender            5742
capital-gain      5742
capital-loss      5742
hours-per-week    5742
native-country    5742
salary            5742
dtype: int64

In [53]:
high_earner.loc[high_earner['hours-per-week']<=40].count()

age               5945
workclass         5945
fnlwgt            5945
education         5945
education-num     5945
marital-status    5945
occupation        5945
relationship      5945
race              5945
gender            5945
capital-gain      5945
capital-loss      5945
hours-per-week    5945
native-country    5945
salary            5945
dtype: int64